apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: "2025-08-05T08:56:17Z"
  labels:
    endpointslice.kubernetes.io/skip-mirror: "true"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:endpointslice.kubernetes.io/skip-mirror: {}
      f:subsets: {}
    manager: kube-apiserver
    operation: Update
    time: "2025-08-05T08:56:17Z"
  name: kubernetes
  namespace: default
  resourceVersion: "234"
  uid: ef2bf0ce-c1b2-47f0-ac2c-5ab27497bebc
subsets:
- addresses:
  - ip: 172.18.0.2
  ports:
  - name: https
    port: 6443
    protocol: TCP
