apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDBTCCAe2gAwIBAgIILY93TCxo7Q0wDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
    AxMKa3ViZXJuZXRlczAeFw0yNTA4MDYwNzQzMjNaFw0zNTA4MDQwNzQ4MjNaMBUx
    EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
    AoIBAQDAnph62leRK8C9i27lDRSXB0SDTpm0VS28QKIMr/cYDCg24OdhmIIKee5v
    kHuwac1pQ9UQF2aciVqmxCW1mXT2cvpCIcbGHRWKIihYhN4AshpcUbuJBZ82jKcY
    dJlIkGAlsNPwH3sveirmJ+T3AEavrcWrD0pRFyIFkY7hgtEcUgzHjzTGfYZc34Dl
    NLxntxEKmaBLlG7WvuMMKd5FTvSFQjlO7EkrkP60BA/4W/UmHkGJ2/O9D9IhZiML
    X+3eMTBv3Tf2Uoxn4EHgjWg7xIDGzLP0nK9JtxsXZCyEERWN6bkdzhdfZezJBOhk
    EvW645Hsf+eHFbLnakadIRWBYvTtAgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP
    BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQnvP3cFK+P2/byzQV0ZLcgHIdu6zAV
    BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQCpcb6dfHw8
    1+X/X7iuGRTKEu5wWmP1ddayE3Z9haGUgNOjfDknqm1DWw2MpH7x03p5Jkvej9J9
    2Ha2ywDozjdBik6uSL2AFQxQubxsMPVMbjvAicuSGW3KRLYdkzQ4y5kycuX1LLgg
    +zD/51Pa+XDl6dGf1H6/HGoBJ5/2y3PKSF2R8+mk9T25q51B+JLtEVFzbMMSq31T
    ZHFnOP3YPPWHTxpoPchL/iHZf9XQXJh89t38fwe84kMy0FXNOeugzU16ZSVcjGB4
    oewmUjv3tv+TJN4pw6YJx9liNgyfoOQTFbl9R3iWXp8eCDoxoOswQNJvOF2yaHMs
    hxYjKCkOAzVF
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  annotations:
    kubernetes.io/description: Contains a CA bundle that can be used to verify the
      kube-apiserver when using internal endpoints such as the internal service IP
      or kubernetes.default.svc. No other usage is guaranteed across distributions
      of Kubernetes clusters.
  creationTimestamp: "2025-08-06T07:48:37Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:ca.crt: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubernetes.io/description: {}
    manager: kube-controller-manager
    operation: Update
    time: "2025-08-06T07:48:37Z"
  name: kube-root-ca.crt
  namespace: default
  resourceVersion: "388"
  uid: eb0632a0-fefb-4f2d-aafb-f45d27aef087
