addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints:
- addresses:
  - 10.244.2.2
  conditions:
    ready: true
    serving: true
    terminating: false
  nodeName: source-cluster-worker
  targetRef:
    kind: Pod
    name: guestbook-frontend-77fdb4f98b-l6p4z
    namespace: default
    uid: 8cc29210-2db7-4c61-ab6d-e4ab01649aaa
- addresses:
  - 10.244.1.3
  conditions:
    ready: true
    serving: true
    terminating: false
  nodeName: source-cluster-worker2
  targetRef:
    kind: Pod
    name: guestbook-frontend-77fdb4f98b-ctkk6
    namespace: default
    uid: 30e1d8d8-adde-4df8-85cc-2e66a446852a
- addresses:
  - 10.244.1.2
  conditions:
    ready: true
    serving: true
    terminating: false
  nodeName: source-cluster-worker2
  targetRef:
    kind: Pod
    name: guestbook-frontend-77fdb4f98b-47nxg
    namespace: default
    uid: 98d39a02-6b28-4423-9f2d-a095b0e16f6d
kind: EndpointSlice
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2025-08-06T08:14:58Z"
  creationTimestamp: "2025-08-06T08:14:25Z"
  generateName: guestbook-frontend-
  generation: 3
  labels:
    app: guestbook
    component: frontend
    endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
    kubernetes.io/service-name: guestbook-frontend
  managedFields:
  - apiVersion: discovery.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:addressType: {}
      f:endpoints: {}
      f:metadata:
        f:annotations:
          .: {}
          f:endpoints.kubernetes.io/last-change-trigger-time: {}
        f:generateName: {}
        f:labels:
          .: {}
          f:app: {}
          f:component: {}
          f:endpointslice.kubernetes.io/managed-by: {}
          f:kubernetes.io/service-name: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"333288b7-e8aa-4e10-bd11-b3fd8e06ed83"}: {}
      f:ports: {}
    manager: kube-controller-manager
    operation: Update
    time: "2025-08-06T08:14:59Z"
  name: guestbook-frontend-tf8lz
  namespace: default
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Service
    name: guestbook-frontend
    uid: 333288b7-e8aa-4e10-bd11-b3fd8e06ed83
  resourceVersion: "2992"
  uid: 0b177e64-a022-4d97-b537-08f2ce96ab87
ports:
- name: http
  port: 80
  protocol: TCP
