apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-08-06T08:14:25Z"
  generateName: guestbook-frontend-77fdb4f98b-
  labels:
    app: guestbook
    component: frontend
    pod-template-hash: 77fdb4f98b
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:generateName: {}
        f:labels:
          .: {}
          f:app: {}
          f:component: {}
          f:pod-template-hash: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"2cca0190-95ac-404e-9107-b6898f628cce"}: {}
      f:spec:
        f:containers:
          k:{"name":"frontend"}:
            .: {}
            f:env:
              .: {}
              k:{"name":"GET_HOSTS_FROM"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"REDIS_MASTER_SERVICE_HOST"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"REDIS_MASTER_SERVICE_PORT"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"REDIS_SLAVE_SERVICE_HOST"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"REDIS_SLAVE_SERVICE_PORT"}:
                .: {}
                f:name: {}
                f:value: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:ports:
              .: {}
              k:{"containerPort":80,"protocol":"TCP"}:
                .: {}
                f:containerPort: {}
                f:protocol: {}
            f:resources:
              .: {}
              f:limits:
                .: {}
                f:cpu: {}
                f:memory: {}
              f:requests:
                .: {}
                f:cpu: {}
                f:memory: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext: {}
        f:terminationGracePeriodSeconds: {}
    manager: kube-controller-manager
    operation: Update
    time: "2025-08-06T08:14:25Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"ContainersReady"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Initialized"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"PodReadyToStartContainers"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
        f:containerStatuses: {}
        f:hostIP: {}
        f:hostIPs: {}
        f:phase: {}
        f:podIP: {}
        f:podIPs:
          .: {}
          k:{"ip":"10.244.1.3"}:
            .: {}
            f:ip: {}
        f:startTime: {}
    manager: kubelet
    operation: Update
    subresource: status
    time: "2025-08-06T08:14:58Z"
  name: guestbook-frontend-77fdb4f98b-ctkk6
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: guestbook-frontend-77fdb4f98b
    uid: 2cca0190-95ac-404e-9107-b6898f628cce
  resourceVersion: "2978"
  uid: 30e1d8d8-adde-4df8-85cc-2e66a446852a
spec:
  containers:
  - env:
    - name: GET_HOSTS_FROM
      value: dns
    - name: REDIS_MASTER_SERVICE_HOST
      value: redis-master
    - name: REDIS_MASTER_SERVICE_PORT
      value: "6379"
    - name: REDIS_SLAVE_SERVICE_HOST
      value: redis-slave
    - name: REDIS_SLAVE_SERVICE_PORT
      value: "6379"
    image: gcr.io/google-samples/gb-frontend:v5
    imagePullPolicy: IfNotPresent
    name: frontend
    ports:
    - containerPort: 80
      protocol: TCP
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 250m
        memory: 64Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-rmppr
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: source-cluster-worker2
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-rmppr
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-08-06T08:14:58Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-08-06T08:14:25Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-08-06T08:14:58Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-08-06T08:14:58Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-08-06T08:14:25Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://6a9e093048e0495386691fe59649e3403efc998b631a4766682bcadab7b72eee
    image: gcr.io/google-samples/gb-frontend:v5
    imageID: gcr.io/google-samples/gb-frontend@sha256:a908df8486ff66f2c4daa0d3d8a2fa09846a1fc8efd65649c0109695c7c5cbff
    lastState: {}
    name: frontend
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-08-06T08:14:57Z"
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-rmppr
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 172.18.0.4
  hostIPs:
  - ip: 172.18.0.4
  phase: Running
  podIP: 10.244.1.3
  podIPs:
  - ip: 10.244.1.3
  qosClass: Burstable
  startTime: "2025-08-06T08:14:25Z"
