apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"guestbook","component":"frontend"},"name":"guestbook-frontend","namespace":"default"},"spec":{"ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"guestbook","component":"frontend"},"type":"ClusterIP"}}
  creationTimestamp: "2025-08-06T08:14:25Z"
  labels:
    app: guestbook
    component: frontend
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:app: {}
          f:component: {}
      f:spec:
        f:internalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":80,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2025-08-06T08:14:25Z"
  name: guestbook-frontend
  namespace: default
  resourceVersion: "2877"
  uid: 333288b7-e8aa-4e10-bd11-b3fd8e06ed83
spec:
  clusterIP: 10.96.126.87
  clusterIPs:
  - 10.96.126.87
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: guestbook
    component: frontend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
